# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.

    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendAzureRmResourceGroupName: 'resource-group-duvan-garcia'
    backendAzureRmStorageAccountName: 'storageduvan'
    backendAzureRmContainerName: 'storageduvan'
    backendAzureRmKey: 'Rr0t+jYUM8DY5aWI69el3PD2eve/FzJEWQz/QBq+w0M1MIeI3uIXqsBYsYyB1ejb7lM8PA4JoSGg+ASt8kbiMg=='

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'