trigger:

  - none
resources:
  repositories:
  - repository: templates
    name: template-pipeline
    type: git


extends:
  template: pipeline/main.yml@templates
  parameters:
      language: java
      build: gradle
      type: api