# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'servicio_Duvan'
    backendAzureRmResourceGroupName: 'resource-group-duvan-garcia'
    backendAzureRmStorageAccountName: 'storageduvan'
    backendAzureRmContainerName: 'storageduvan'
    backendAzureRmKey: 'xCy4e9uqb62Sd7fIk1jdjYGRUadG6wJT96TvsTRFv/LuR39nGyu4z5qXpTPbxS+LCPFrQAMdPcQL+AStYlNZDQ=='

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(codelab.microsoft.storageduvan'
    environmentServiceNameAzureRM: 'servicio_Duvan'
    
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'servicio_Duvan'

#test


