apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-back
  namespace: #{Environment}#
spec:
  selector:
    matchLabels:
      app: calculator
  replicas: 3
  template:
    metadata:
      annotations:
        buildnumber: "#{Build.BuildId}#"
      labels:
       app: calculator
    spec:
     containers:
     - name: calculator
       image: "cristiancontainer.azurecr.io/#{Environment}#-#{ImageName}#:#{Build.BuildNumber}#"
       imagePullPolicy: Always
       ports:
       - containerPort: 8080
     imagePullSecrets: 
     - name: docker-secret

---

apiVersion: v1
kind: Service
metadata:
  name: deploy-back
  namespace: #{Environment}#
spec:
  selector:
    app: calculator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer

