name: Crear Proyecto SonarCloud

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar dependencias Python
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Crear Proyecto SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: python create_sonarcloud_project.py

