name: Crear Proyecto SonarCloud

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SonarCloud Project
        run: |
          # Configura las variables necesarias
          export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
          export ORGANIZATION_KEY=duvanquind
          export PROJECT_KEY=123quind
          export PROJECT_NAME=test-calculadora

          # Crea el proyecto en SonarCloud utilizando la API
          curl -X POST -u "$SONAR_TOKEN:" \
            -d "name=$PROJECT_NAME" \
            -d "project=$PROJECT_KEY" \
            -d "organization=$ORGANIZATION_KEY" \
            "https://sonarcloud.io/api/projects/create"
