name: Crear Proyecto SonarCloud

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SonarCloud Project
        run: |
          # Configura las variables necesarias
          export TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}
          export ORGANIZATION_KEY=duvanquind
          export PROJECT_KEY=1234quind
          export PROJECT_NAME=test-calculadora
          curl -X POST -u "$TOKEN_GITHUB:" \
            -d "name=$PROJECT_NAME" \
            -d "project=$PROJECT_KEY" \
            -d "organization=$ORGANIZATION_KEY" \
            "https://sonarcloud.io/api/projects/create"



