name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: imprime hola
        run: echo "hola mundo"
